- name: Create an instance
  os_server:
    name: '{{item.0.instance_name}}'
    image: '{{ item.0.instance_image }}'
    key_name: '{{ item.0.instance_key_name }}'
    flavor: '{{ item.0.instance_flavor}}'
    availability_zone: '{{availability_zone}}'
    security_groups: '{{ sg_names }}'
    volumes: '{{item.1}}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance
  with_together:
    - "{{ instances }}"
    - "{{ os_vol_ids }}"

- debug:
    msg: "Instance {{ instance_name}} has been created. IP address is {{ os_instance.openstack.public_v4}}"
  when: os_instance.openstack is defined