#install dependencies on the host
- name: install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"


- name: Install openstacksdk
  become: yes
  pip:
    name: ["openstacksdk"]
    state: latest


