
# - name: Proxy_env
#   become: true
#   copy:
#     src: ./file/environment
#     dest: /etc/environment
#     mode: 0755

- name: Install dependencies
  tags: always
  become: yes
  apt:
    name: [ 'python3', 'python3-setuptools', 'python3-pip',]
    state: latest
    install_recommends: no

- name: Pip
  raw: 
    pip3 install cloudant;
    pip3 install geotext;
    pip3 install vaderSentiment;
    pip3 install tweepy;
    pip3 install pprint;

- name: Delete exist file
  raw: sudo rm -rf /home/ubuntu/CCCproject2-team56
- name: Download python File
  raw: git clone https://github.com/Fish-WY/CCCproject2-team56
