
- name: Bulid cluster
  raw: 
    curl -X POST -H "Content-Type:application/json" http://admin:admin@"{{ansible_default_ipv4.address}}":5984/_cluster_setup -d '{"action":"enable_cluster", "bind_address":"0.0.0.0", "username":"admin", "password":"admin", "port":5984, "node_count":"3", "remote_node":"{{ groups['dbserver'][1] }}", "remote_current_user":"admin", "remote_current_password":"admin" }';
    curl -X POST -H "Content-Type:application/json" http://admin:admin@"{{ansible_default_ipv4.address}}":5984/_cluster_setup -d '{"action":"add_node", "host":"{{ groups['dbserver'][1] }}", "port":5984, "username":"admin", "password":"admin"}';
    curl -X POST -H "Content-Type:application/json" http://admin:admin@"{{ansible_default_ipv4.address}}":5984/_cluster_setup -d '{"action":"enable_cluster", "bind_address":"0.0.0.0", "username":"admin", "password":"admin", "port":5984, "node_count":"3", "remote_node":"{{ groups['dbserver'][2] }}", "remote_current_user":"admin", "remote_current_password":"admin" }';
    curl -X POST -H "Content-Type:application/json" http://admin:admin@"{{ansible_default_ipv4.address}}":5984/_cluster_setup -d '{"action":"add_node", "host":"{{ groups['dbserver'][2] }}", "port":5984, "username":"admin", "password":"admin"}';
    
- name: Finish cluster
  raw:
    curl -X POST -H "Content-Type:application/json" http://admin:admin@"{{ansible_default_ipv4.address}}":5984/_cluster_setup -d '{"action":"finish_cluster"}';

- name: Delete nonode
  raw: 
    rev=`curl -XGET "http://{{ansible_default_ipv4.address}}:5986/_nodes/nonode@nohost" --user "admin:admin" | sed -e 's/[{}"]//g' | cut -f3 -d:`;
    curl -X DELETE "http://{{ansible_default_ipv4.address}}:5986/_nodes/nonode@nohost?rev=${rev}"  --user "admin:admin"